---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: undercroft
spec:
  encryptedData:
    api-key: AgAUHkHune3WyFZeJncJWQSLDHBjvRmTRdxznYZN+bNxDtBDL6e4QSTMX1ZPhum2YIdsQ2wbr+E7MfzmWrC732040kgFdgSUCKpgLwCmYpLValI8iDgVQPz03LLbIqUUm3CUApYV6LkOhHCxlq8iaFrlhQpqrbZzuxD0wn7D+vjKQHZcjyVdPSAPkTjw3J/pHs0fet+JCe+2gI7hXwaaM3GkgAWQrR7AD9ykhOvxSEOpFo1hERAFrzIXF1WCE9Ocuqg3gRGeXNNfpXHSai1/kS9Fzxz14nIGHVqZdYuDnjXEcz1/U/yWFzyINVKlsD0tLlj0KAH6oxOcGM8x6wMknU5KrwKcuKrFIlyiEeIFie+bJs/48ljtbJwrdNN5RA/KMDmkStfdXAgK4dndVu/GlmsjNb9sZRe8UnB1ocdXkbRyNBZhbSkTYp6LZXDhGjQDhHFK3IvLq4uKMeFcK0+DCUJ67/jwdLmVo//PtZc5C/8R1Y9NEbgMXLlXhFgGntJj/XCsZxMD0KHrN4CBtzDCtiFGCrP2kPPpi8O+3pptGywKtRtuYfm1Zp/VVTwl8VFB5QnpTj78mDcpW6nhx501XEkt6WB2rodnYyOdY3rjkz4FTvOqsOxPBFep6qxdJfuom2sd31tPhJj6SfAihJk5KS0hA1ClGK8bdqUUIbs82vSJXrD4pDppRZHfwNxJxVkd28X3gNdil+uT
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: undercroft
