apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-metrics
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gateway
  endpoints:
    - targetPort: 8000
      path: /metrics
      interval: 15s